# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-02 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('user', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('ratings', models.TextField()),
                ('average_rating', models.DecimalField(decimal_places=3, default=None, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Sim_scores',
            fields=[
                ('movie_id', models.TextField(default=None, primary_key=True, serialize=False)),
                ('scores', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('movie_id', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('movie_title', models.TextField(blank=True, null=True)),
                ('genres', models.BinaryField(blank=True, null=True)),
                ('actors', models.BinaryField(blank=True, null=True)),
                ('writers', models.BinaryField(blank=True, null=True)),
                ('producers', models.BinaryField(blank=True, null=True)),
                ('cinematographer', models.BinaryField(blank=True, null=True)),
                ('director', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpdateDB',
            fields=[
                ('update_number', models.IntegerField(primary_key=True, serialize=False)),
                ('titles_lines_to_skip', models.BigIntegerField()),
                ('professions_lines_to_skip', models.BigIntegerField()),
            ],
        ),
    ]
