# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-04 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_recommender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='actors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='titles',
            name='cinematographer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='titles',
            name='director',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='titles',
            name='genres',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='titles',
            name='producers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='titles',
            name='writers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
